# Use the official Node.js image.
FROM node:14 AS build

# Create and change to the app directory.
WORKDIR /client

# Copy the package.json and package-lock.json files.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . /client/

# Build the app.
RUN npm run build

# Use an Nginx image to serve the built app.
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Expose the port the app runs on.
EXPOSE 8001

# Start Nginx.
CMD ["nginx", "-g", "daemon off;"]
